version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000" 
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - ryde-network

  frontend:
    build: ./frontend
    ports:
      - "5173:4173" 
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    networks:
      - ryde-network

networks:
  ryde-network:
    driver: bridge
